/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metode;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel;
import pola_kompetensi.dashboard;
import pola_kompetensi.kelola_data;
import kesimpulan.hasil;

/**
 *
 * @author Supandi
 */
public class ARM extends javax.swing.JFrame {

    /**
     * Creates new form ARM
     */
    public static hasil kesimpulan = new hasil();
    public ArrayList<String[]> parseData = new ArrayList<>();
    public ArrayList<String> cleanData = new ArrayList<>();
    public ArrayList<String[]> rules = new ArrayList<String[]>();
    public ArrayList<Object[]> listsHasil = new ArrayList<Object[]>();
    public int batasMinimum;
    public Frekuensi frekuensi;
    public AssociationRuleMining associationRuleMining;
    
    public ARM() {
        initComponents();
    }
    
    public void setAttributes(ArrayList<String[]> parseData, ArrayList<String> cleanData, int batasMinimum){
        this.parseData = (ArrayList<String[]>)parseData.clone();
        this.cleanData = (ArrayList<String>)cleanData.clone();
        this.batasMinimum = batasMinimum;
        
        frekuensi = new Frekuensi(parseData, cleanData, batasMinimum);
        frekuensi.generateTableTransaction();
        frekuensi.getSumTransactions();
        frekuensi.getMinimumTransactions(batasMinimum);
        frekuensi.getCombination();
        
        associationRuleMining = new AssociationRuleMining(frekuensi.sumOfCombination, frekuensi.tableTransaction);
        associationRuleMining.buildRule();
        rules = (ArrayList<String[]>)associationRuleMining.rules.clone();
        
        buildAssociationTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bcg1 = new pola_kompetensi.bcg();
        panelWarnaTransparan1 = new Tampilan.PanelWarnaTransparan();
        jLabel5 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_AR1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_AR2 = new javax.swing.JTable();
        btnproses_arm1 = new Tampilan.button1();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        SubHome = new javax.swing.JMenuItem();
        SubKD = new javax.swing.JMenuItem();
        SubExit = new javax.swing.JMenuItem();
        Menu_View = new javax.swing.JMenu();
        SubMenu_ARM = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        submenu_result = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analisis Association Rule");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tabel Association Rule ");

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("%");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Minimum Support");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("50");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Minimum Confidence");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("50");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("%");

        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });

        Table_AR1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "If antecedent then consequent", "Support", "Confidence", "support x confidence"
            }
        ));
        jScrollPane2.setViewportView(Table_AR1);
        if (Table_AR1.getColumnModel().getColumnCount() > 0) {
            Table_AR1.getColumnModel().getColumn(2).setResizable(false);
        }

        Table_AR2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "If antecedent then consequent", "Support", "Confidence"
            }
        ));
        jScrollPane3.setViewportView(Table_AR2);
        if (Table_AR2.getColumnModel().getColumnCount() > 0) {
            Table_AR2.getColumnModel().getColumn(2).setResizable(false);
        }

        btnproses_arm1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnproses_arm1.setForeground(new java.awt.Color(255, 255, 255));
        btnproses_arm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/loading-circles.png"))); // NOI18N
        btnproses_arm1.setText("Lihat Hasil");
        btnproses_arm1.setFont(new java.awt.Font("Clarendon Lt BT", 1, 18)); // NOI18N
        btnproses_arm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproses_arm1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelWarnaTransparan1Layout = new javax.swing.GroupLayout(panelWarnaTransparan1);
        panelWarnaTransparan1.setLayout(panelWarnaTransparan1Layout);
        panelWarnaTransparan1Layout.setHorizontalGroup(
            panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarnaTransparan1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelWarnaTransparan1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelWarnaTransparan1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelWarnaTransparan1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel15))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelWarnaTransparan1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(29, 29, 29)
                        .addGroup(panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelWarnaTransparan1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelWarnaTransparan1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWarnaTransparan1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(panelWarnaTransparan1Layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(btnproses_arm1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWarnaTransparan1Layout.createSequentialGroup()
                    .addContainerGap(36, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)))
        );
        panelWarnaTransparan1Layout.setVerticalGroup(
            panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarnaTransparan1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(165, 165, 165)
                .addGroup(panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15))
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17))
                    .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnproses_arm1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(panelWarnaTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelWarnaTransparan1Layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(417, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout bcg1Layout = new javax.swing.GroupLayout(bcg1);
        bcg1.setLayout(bcg1Layout);
        bcg1Layout.setHorizontalGroup(
            bcg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bcg1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelWarnaTransparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        bcg1Layout.setVerticalGroup(
            bcg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bcg1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelWarnaTransparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        jMenu1.setText("Identifikasi Pola");

        SubHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/homepage.png"))); // NOI18N
        SubHome.setText("Home");
        SubHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubHomeActionPerformed(evt);
            }
        });
        jMenu1.add(SubHome);

        SubKD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/checklist-with-a-pencil.png"))); // NOI18N
        SubKD.setText("Kelola Data");
        SubKD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubKDActionPerformed(evt);
            }
        });
        jMenu1.add(SubKD);

        SubExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/exit.png"))); // NOI18N
        SubExit.setText("Exit");
        SubExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubExitActionPerformed(evt);
            }
        });
        jMenu1.add(SubExit);

        jMenuBar1.add(jMenu1);

        Menu_View.setText("Association");
        Menu_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ViewActionPerformed(evt);
            }
        });

        SubMenu_ARM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/calculator.png"))); // NOI18N
        SubMenu_ARM.setText("ARM");
        SubMenu_ARM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenu_ARMActionPerformed(evt);
            }
        });
        Menu_View.add(SubMenu_ARM);

        jMenuBar1.add(Menu_View);

        jMenu2.setText("Hasil Asosiasi");

        submenu_result.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/text-documents.png"))); // NOI18N
        submenu_result.setText("Lihat Kesimpulan");
        submenu_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_resultActionPerformed(evt);
            }
        });
        jMenu2.add(submenu_result);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bcg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bcg1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubHomeActionPerformed
        this.setVisible(false);
        new dashboard().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_SubHomeActionPerformed

    private void SubKDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubKDActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new kelola_data().setVisible(true);
    }//GEN-LAST:event_SubKDActionPerformed

    private void SubExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubExitActionPerformed
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"Apakah anda mau keluar ?","Konfirmasi Keluar",JOptionPane.YES_NO_OPTION);
        if (ok==0){
            dispose();
        }
    }//GEN-LAST:event_SubExitActionPerformed

    private void SubMenu_ARMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenu_ARMActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ARM().setVisible(true);
    }//GEN-LAST:event_SubMenu_ARMActionPerformed

    private void Menu_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_ViewActionPerformed

    private void submenu_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_resultActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ARM.kesimpulan.setVisible(true);
    }//GEN-LAST:event_submenu_resultActionPerformed

    private void btnproses_arm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproses_arm1ActionPerformed
        // TODO add your handling code here:
        int i,j,idx=1;
        
        listsHasil = (ArrayList<Object[]>)associationRuleMining.getMinimumSupportAndConfidenceLists(rules, (int)jSlider1.getValue(), (int)jSlider2.getValue()).clone();
        
        DefaultTableModel tabelModel = new DefaultTableModel(){};
        tabelModel.addColumn("No");
        tabelModel.addColumn("If antecedent then consequent");
        tabelModel.addColumn("Support");
        tabelModel.addColumn("Confidence");
        tabelModel.addColumn("Support x Confidence");
        
        for(i=0;i<listsHasil.size();i++){
            Object[] data = new Object[5];
            data[0] = idx;
            data[1] = listsHasil.get(i)[1];
            data[2] = listsHasil.get(i)[2]+"%";
            data[3] = listsHasil.get(i)[3]+"%";
            data[4] = listsHasil.get(i)[4];
            tabelModel.addRow(data);
            idx++;
        }
        
        Table_AR1.setModel(tabelModel);
        
        kesimpulan.setAttribute(listsHasil);
        kesimpulan.buildConclusion();
    }//GEN-LAST:event_btnproses_arm1ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        jLabel15.setText(String.valueOf(jSlider1.getValue()));
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        // TODO add your handling code here:
        jLabel17.setText(String.valueOf(jSlider2.getValue()));
    }//GEN-LAST:event_jSlider2StateChanged
    
   private void buildAssociationTable(){
       DefaultTableModel tabelModel = new DefaultTableModel(){};    
       tabelModel.addColumn("No");
       tabelModel.addColumn("If antecedent then consequent");
       tabelModel.addColumn("Support");
       tabelModel.addColumn("Confidence");
       
       try{
            for(int i=0;i<rules.size(); i++){
                Object[] x = new Object[4];
                x[0] = (i+1);
                x[1] = rules.get(i)[1];
                x[2] = Math.round(Double.parseDouble(rules.get(i)[3]))+"%";
                x[3] = Math.round(Double.parseDouble(rules.get(i)[4]))+"%";
                tabelModel.addRow(x);
            }
            Table_AR2.setModel(tabelModel);
        }catch(Exception ex){
        }
   }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ARM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ARM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ARM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ARM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ARM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_View;
    private javax.swing.JMenuItem SubExit;
    private javax.swing.JMenuItem SubHome;
    private javax.swing.JMenuItem SubKD;
    private javax.swing.JMenuItem SubMenu_ARM;
    private javax.swing.JTable Table_AR1;
    private javax.swing.JTable Table_AR2;
    private pola_kompetensi.bcg bcg1;
    private Tampilan.button1 btnproses_arm1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private Tampilan.PanelWarnaTransparan panelWarnaTransparan1;
    private javax.swing.JMenuItem submenu_result;
    // End of variables declaration//GEN-END:variables
}
