/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pola_kompetensi;

import metode.ARM;
import kesimpulan.hasil;
import javax.swing.JOptionPane; 
/**
 *
 * @author Supandi
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bcg1 = new pola_kompetensi.bcg();
        txt1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        SubHome = new javax.swing.JMenuItem();
        SubKD = new javax.swing.JMenuItem();
        SubExit = new javax.swing.JMenuItem();
        Menu_View = new javax.swing.JMenu();
        SubMenu_ARM = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        submenu_result = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        txt1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setText("IDENTIFIKASI POLA KOMPETENSI TEKNOLOGI INFORMASI DAN KOMUNIKASI");

        txt2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        txt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Logo Unjani 1.png"))); // NOI18N

        txt3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        txt3.setForeground(new java.awt.Color(255, 255, 255));
        txt3.setText("BERDASARKAN KEBUTUHHAN INDUSTRI MENGGUNAKAN");

        txt4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        txt4.setForeground(new java.awt.Color(255, 255, 255));
        txt4.setText("ASSOCIATION RULE");

        javax.swing.GroupLayout bcg1Layout = new javax.swing.GroupLayout(bcg1);
        bcg1.setLayout(bcg1Layout);
        bcg1Layout.setHorizontalGroup(
            bcg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bcg1Layout.createSequentialGroup()
                .addGroup(bcg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bcg1Layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bcg1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(txt1))
                    .addGroup(bcg1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(txt3))
                    .addGroup(bcg1Layout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addComponent(txt4)))
                .addContainerGap(2045, Short.MAX_VALUE))
        );
        bcg1Layout.setVerticalGroup(
            bcg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bcg1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(txt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt3)
                .addGap(18, 18, 18)
                .addComponent(txt4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 609, Short.MAX_VALUE)
                .addGroup(bcg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125))
        );

        jMenu1.setText("Identifikasi Pola");

        SubHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/homepage.png"))); // NOI18N
        SubHome.setText("Home");
        SubHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubHomeActionPerformed(evt);
            }
        });
        jMenu1.add(SubHome);

        SubKD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/checklist-with-a-pencil.png"))); // NOI18N
        SubKD.setText("Kelola Data");
        SubKD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubKDActionPerformed(evt);
            }
        });
        jMenu1.add(SubKD);

        SubExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/exit.png"))); // NOI18N
        SubExit.setText("Exit");
        SubExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubExitActionPerformed(evt);
            }
        });
        jMenu1.add(SubExit);

        jMenuBar1.add(jMenu1);

        Menu_View.setText("Association");
        Menu_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ViewActionPerformed(evt);
            }
        });

        SubMenu_ARM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/calculator.png"))); // NOI18N
        SubMenu_ARM.setText("ARM");
        SubMenu_ARM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenu_ARMActionPerformed(evt);
            }
        });
        Menu_View.add(SubMenu_ARM);

        jMenuBar1.add(Menu_View);

        jMenu2.setText("Hasil Asosiasi");

        submenu_result.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/text-documents.png"))); // NOI18N
        submenu_result.setText("Lihat Kesimpulan");
        submenu_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_resultActionPerformed(evt);
            }
        });
        jMenu2.add(submenu_result);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bcg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bcg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubHomeActionPerformed
        this.setVisible(false);
        new dashboard().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_SubHomeActionPerformed

    private void SubKDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubKDActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new kelola_data().setVisible(true);
    }//GEN-LAST:event_SubKDActionPerformed

    private void SubExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubExitActionPerformed
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"Apakah anda mau keluar ?","Konfirmasi Keluar",JOptionPane.YES_NO_OPTION);
        if (ok==0){
            dispose();
        }
    }//GEN-LAST:event_SubExitActionPerformed

    private void SubMenu_ARMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenu_ARMActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ARM().setVisible(true);
    }//GEN-LAST:event_SubMenu_ARMActionPerformed

    private void Menu_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_ViewActionPerformed

    private void submenu_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_resultActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ARM.kesimpulan.setVisible(true);
    }//GEN-LAST:event_submenu_resultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_View;
    private javax.swing.JMenuItem SubExit;
    private javax.swing.JMenuItem SubHome;
    private javax.swing.JMenuItem SubKD;
    private javax.swing.JMenuItem SubMenu_ARM;
    private pola_kompetensi.bcg bcg1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem submenu_result;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    // End of variables declaration//GEN-END:variables
}
